server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: userapp-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: wallapp-service
          uri: http://localhost:8082
          predicates:
            - Path=/wallApp/posts/**,/wallApp/notifications/**
        - id: searchapp-service
          uri: http://localhost:8083
          predicates:
            - Path=/search/**
        - id: messagesapp-service
          uri: http://localhost:8084
          predicates:
            - Path=/messages/**

         
