apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagesapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messagesapp
  template:
    metadata:
      labels:
        app: messagesapp
    spec:
      containers:
        - name: messagesapp
          image: minatamer/messagesapp:1.0
          ports:
            - containerPort: 8080
          env:
            # RabbitMQ
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongodb-service"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "facebook_messaging"
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://root:example@mongodb-service:27017/facebook_messaging?authSource=admin"
            - name: SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED
              value: "false"
