apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==     # "root"
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ== # "example"
#  URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvOjI3MDE3L25vdGlmaWNhdGlvbl9kYj9hdXRoU291cmNlPWFkbWlu
  MESSAGES_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvOjI3MDE3L2ZhY2Vib29rX21lc3NhZ2luZz9hdXRoU291cmNlPWFkbWlu
  POSTS_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvOjI3MDE3L3Bvc3Q/YXV0aFNvdXJjZT1hZG1pbg==
  # "mongodb://root:example@mongo-0.mongo:27017/notification_db?authSource=admin"