apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchapp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchapp-service
  template:
    metadata:
      labels:
        app: searchapp-service
    spec:
      containers:
        - name: searchapp-service
          image: minatamer/searchapp:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://root:example@mongo-0.mongo:27017/search?authSource=admin"
            - name: user.service.url
              value: http://userapp-service:8080/user
            - name: wall.service.url
              value: http://wallapp-service:8080/wallApp/posts
            - name: SPRING_APPLICATION_NAME
              value: searchapp-service
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongo-0.mongo"
