apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallapp
  template:
    metadata:
      labels:
        app: wallapp
    spec:
      containers:
        - name: wallapp
          image: minatamer/wallapp:1.0
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://root:example@mongodb-service:27017/post?authSource=admin"
