version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: facebook_messaging
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "root", "-p", "example"]
      interval: 5s
      timeout: 30s
      retries: 3

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 30s
      retries: 3

#  messaging-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATA_MONGODB_HOST: mongo
#      SPRING_RABBITMQ_HOST: rabbitmq
#      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017/facebook_messaging?authSource=admin
#      SPRING_DATA_MONGODB_DATABASE: facebook_messaging
#    depends_on:
#      mongo:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#    restart: always