services:
  postgres:
    image: postgres
    container_name: facebook-replica-db
    environment:
      POSTGRES_DB: facebook-replica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  redis_cache:
    image: redis:latest
    container_name: redisCache_facebook-replica
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisInsight_facebook-replica
    ports:
      - "5540:5540"
    restart: always